In [71]:
import numpy as np
import matplotlib.pyplot as plt

In [72]:
#Declare your matrix here
S = np.array([[10, 3],[3, 6]])
S

array([[10,  3],
       [ 3,  6]])

In [73]:
#Intitialize a vector - use random non-zero values
x = np.array([3, 5])
x

array([3, 5])

In [74]:
#Define your accuracy here
accuracy = 0.00001

In [75]:
def iter_algo(S , x, accuracy):
    x_c = []
    y_c = []
    x_new = x / np.linalg.norm(x)
    x_old = np.array([0, 0])
    i = 0
    while abs(np.linalg.norm(x_new - x_old)) >= accuracy:
        x_old = x_new
        x_new = np.dot(S, x_new)
        x_new = x_new / np.linalg.norm(x_new)
        x_c.append(x_new[0])
        y_c.append(x_new[1])
        i += 1
    lambd = np.dot(S,x_new) / x_new
    return x_new, lambd[0], i
    

In [76]:
eigen_vector, largest_eigen_value, iterations = iter_algo(S, x, accuracy)

In [77]:
eigen_vector

array([0.88167215, 0.47186251])

In [78]:
largest_eigen_value

11.605571324911251

In [79]:
iterations

12